### ISSUE TITLE
Undefined offset: 0

### ISSUE THREAD

**Issue by Faridbabayev001** [orkhanahmadov/cbar-currency#5]
When I use any rate method without amount parameter (example `$cbar->USD();` ). Show `Undefined offset: 0` error
![image](https://user-images.githubusercontent.com/20392117/93836366-93e6f400-fc93-11ea-9760-03b61fda64da.png)

https://github.com/orkhanahmadov/cbar-currency/blob/c3d76dea0a14c6a0627c3e969a4c3339ee86f81d/src/CBAR.php#L203

**Comment by orkhanahmadov** [comment]
If you want to get a recent USD rate you don't need to call it as a function, get it as property:
``` php
$cbar->USD;
```

"Method fetching" is used to Currency -> AZN conversion, it requires an amount how much you want to convert.

I just released version [1.3.0](https://github.com/orkhanahmadov/cbar-currency/releases/tag/1.3.0) with changes to "method fetching". From now on whenever you call `$cbar->USD()` it will work the same way as `$cbar->USD(1)`

Thanks for reporting @Faridbabayev001 !
